default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: quanlyanh_development

test:
  <<: *default
  database: quanlyanh_test

production:
  <<: *default
  database: quanlyanh_production
  username: quanlyanh
  password: <%= ENV["QUANLYANH_DATABASE_PASSWORD"] %>
